import turtle

isaiah = turtle.Turtle()
paige = turtle.Turtle()
dyson = turtle.Turtle()
jarrett = turtle.Turtle()
isaiah.color("dark slate blue")
dyson.color("aquamarine")
jarrett.color("saddle brown")
paige.color("deep pink")
turtle.pu()
turtle.backward(300)
turtle.pd()
turtle.right(90)
turtle.circle(300)
paige.pu()
paige.goto(70,80)
paige.pd()
paige.right(90)
paige.circle(50)
turtle.exitonclick()