import turtle

isaiah = turtle.Turtle()
paige = turtle.Turtle()
dyson = turtle.Turtle()
jarrett = turtle.Turtle()
isaiah.color("dark slate blue")
dyson.color("aquamarine")
jarrett.color("saddle brown")
paige.color("deep pink")
isaiah.pu()
isaiah.backward(300)
isaiah.pd()
isaiah.right(90)
isaiah.circle(300)
paige.pu()
paige.goto(70,80)
paige.pd()
paige.right(90)
paige.circle(50)
jarrett.pu()
jarrett.goto(-90,80)
jarrett.pd()
jarrett.circle(50)
dyson.pu()
dyson.goto(-110,-110)
dyson.pd()
dyson.left(30)
dyson.forward(60)
dyson.right(60)
dyson.forward(60)
dyson.left(60)
dyson.forward(60)
dyson.right(60)
dyson.forward(60)
turtle.exitonclick()